server:
  port: 9000

spring:
  application:
    name: springboot-demo-mayueyue

  datasource:
    name: test
    url: jdbc:mysql://bj-cdb-nqzzkayy.sql.tencentcdb.com:61097/mayueyue
    username: root
    password: fLeHadrR98C4jt
    driver-class-name: com.mysql.jdbc.Driver



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    com:
      mayueyue:
        mapper: debug
